### PR TITLE
add /github/workspace to git safe.directory 

### PR DESCRIPTION
**Pull request by chenzaichun**
This is just a workaround for #30 .

### CODE REVIEW

**Comment by stefanb** [comment]
It seems this could work!
Not sure how to test it before the merge and release though.

**Comment by benedictdudel** [comment]
I can verify that this workaround fixes the fatal error. If you want to verify you can fork the action and just reference a local action like:

```yaml
 - name: Push changes
        uses: ./packages/commit-action
        with:
             ...
```

**Comment by stefanb** [comment]
Interesting, thanks!

@rusnasonov can this be merged and released, pretty please?

**Review by stefanb — APPROVED** [review]

**Comment by stefanb** [comment]
Thanks, release 2.9 works flawlessly again!

**Pull request merged**
